#!/usr/bin/env bash
# Redirects a user to my github repo with code 301

# Update packages
sudo apt update

# Install nginx
sudo apt install -y nginx

sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Jim-03 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
sudo service nginx reload
