#!/usr/bin/env bash
# 404 not found

# Update packages
sudo apt update

# Install nginx
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Jim-03 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/listen 80 default_server;/a \
    error_page 404 /404.html;\
    location = /404.html {\
        root /var/www/html;\
        internal;\
    }' /etc/nginx/sites-available/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx reload
