#!/usr/bin/env bash
# Displays the PID, along with the process name, of processes whose name contain the word bash

pids=$(pgrep -f bash)

for pid in $pids;
do
	name=$(ps -o comm= -p $pid)
	echo $pid $name
done
