#!/usr/bin/env bash
#script to print best school 10 times but on 9th loop adds hi in the next line

i=0
while [ $i -lt 10 ];
do
	echo 'Best School'
	if (( $i == 8 ));
	then
		echo 'Hi'
	fi
	(( i++ ))
done;
